### ISSUE TITLE
Armour slots and off-hand having their items tossed when hotbar is full

### ISSUE THREAD

**Issue by Jeanfeels** [North-West-Wind/forge-autofish#14]
**Describe the bug**
Presumably this is related to the item filter. Despite having a near empty inventory, when i autofish with the filter enabled, and the hotbar fills up, catching items results in my equipped armour being thrown out of my inventory.

**To Reproduce**
Self explanatory but inconsistent.

**Expected behavior**
Only items in the main inventory that are not in the off hand, armour or hotbar slots should be thrown (if i am understanding the item filter correctly). 

also: 
I am beginning to think i might not fully understand what you intended the item filter to do. And i'm definitely not the only one judging by the comments on curseforge.

You should probably _explain_ what the item filter is supposed to do on the mod page since it is the primary source of my confusion when using this mod and I suspect my understanding of it is flawed.

**Comment by North-West-Wind** [comment]
This should be fixed with v4.0.1
