### ISSUE TITLE
Game crashes when open GUI

### ISSUE THREAD

**Issue by solovozer** [North-West-Wind/forge-autofish#19]
I'm playing on 1.19.3. When pressing K to open he GUI, the game instantly crashes. All other features works as expected and auto-reeling fuctions normally. Further experimentation shows that the problem isn't because of other mods.

**Comment by minecrafterseppe** [comment]
im having the same issue 
ill provide a crash log 
[crash-2023-01-27_11.50.38-client.txt](https://github.com/North-West-Wind/forge-autofish/files/10518087/crash-2023-01-27_11.50.38-client.txt)

**Comment by Adambean** [comment]
Glad it's not just me.
For now just unbind the key to avoid accidentally causing a crash whilst playing. (Use ESC to clear the key during the binding process.)

**Comment by fs910175** [comment]
I have the same problem.
Fortunately it still maintains basic jobs.

**Comment by North-West-Wind** [comment]
Fixed with v5.0.3. Should be available on CurseForge soon.
