### ISSUE TITLE
Jobs+ Fishermans Rod not reeling in

### ISSUE THREAD

**Issue by NewAnnLS** [North-West-Wind/forge-autofish#20]
**Describe the bug**
Seems like Jobs+ rod doesn't quite work like vanilla fishing rod. AutoFish does throw the bobber, but it does not reel it back in.

**To Reproduce**
Use Fishermans Rod from [Jobs+](https://www.curseforge.com/minecraft/mc-mods/jobsplus)
Mod versions: forgeautofish-5.0.2-1.19, JobsPlus 1.19.2-0.9.4, forge 43~ client 1.19.2.

**Expected behavior**
Reel in like with vanilla rods. I didn't test AF with other mods adding fishing rods, but it would be awesome to have it functional.

**Comment by North-West-Wind** [comment]
It seems like Jobs+ fishing bobber fails to return a correct `isInWater` value because the `tick` from parent class is never called. I'm working on a fix that should make it compatible with most other mods.

**Comment by North-West-Wind** [comment]
Fixed in 5.1.0 for 1.19.2
