### ISSUE TITLE
Autofish for 1.20.*

### ISSUE THREAD

**Issue by HaykArakelyan** [North-West-Wind/forge-autofish#29]
Well, I have been using this mod for 1.20.1, and everything is working fine with it. But now I am running Minecraft 1.20.4. So, it found out that the mod works like all features. Except one thing. When I click "K," by which I try to open the settings menu for this mod. The game crashes. I understand that the mod does not support 1.20.4, but I thought that if the mod works, that means some simple and unimportant thing causes it to crash (maybe a filter feature, but not sure). So, I guess it should be a few lines of code to fix this.

Here, I will put the crash log in case you need it. 

[latest.log](https://github.com/North-West-Wind/forge-autofish/files/13773937/latest.log)

Please let me know if you develop it. Thanks in advance, and Good Luck!

**Comment by North-West-Wind** [comment]
Just released 6.0.0-1.20.4 for 1.20.4
