### ISSUE TITLE
Trying to open settings in 1.20.2 crashes

### ISSUE THREAD

**Issue by DraconicNEO** [North-West-Wind/forge-autofish#30]
**Describe the bug**
Any attempt to open the settings in 1.20.2 (Forge 48.1.0) causes the game to crash showing a "saving world" dialog

**To Reproduce**
Get in-game, press the key to open settings, game will crash

**Expected behavior**
It is supposed to open the settings menu so I can change or configure settings.

**Screenshots**
N/A

**Comment by North-West-Wind** [comment]
It may or may not work with the 1.20.4 version. I don't plan to support in between versions.
