### ISSUE TITLE
1.20.4 autofishing stops working after catching 3 fishes

### ISSUE THREAD

**Issue by Mirerew** [North-West-Wind/forge-autofish#31]
**Describe the bug**
Autofishes stops working every time it cought like 3 fish. Then it start to fake fish and reels in nothing

**To Reproduce**
Just use it

**Expected behavior**
Fake fishing

**Comment by North-West-Wind** [comment]
This may be due to server lag. Try turning up the recast delay.

**Comment by North-West-Wind** [comment]
#33 should be a workaround to this
