### ISSUE TITLE
NeoForge Support

### ISSUE THREAD

**Issue by IsaacLiu2009** [North-West-Wind/forge-autofish#32]
Embrace NeoForge for a revitalized Minecraft modding experience. It's a new generation of Forge that prioritizes collaboration and respect, offering a stable platform for your creativity to flourish.

**Comment by North-West-Wind** [comment]
I've tried to make a build and it's currently waiting for approval on CurseForge. I'll close this issue for now. If there happens to be bugs with that build, create new issues for that specifically :)
