### ISSUE TITLE
Request for Timeout-Based Auto-Recast Feature

### ISSUE THREAD

**Issue by Guation** [North-West-Wind/forge-autofish#33]
**Is your feature request related to a problem? Please describe.**  
The auto-fishing mod currently uses the bobber sinking as the condition to detect when a fish is hooked. However, there is sometimes a bug where the client shows the bobber as stuck in a fixed position. On the server side, it appears that the fish is being caught continuously, but the rod is never reeled in.

**Describe the solution you'd like**  
I would like the mod to include a feature where, if the bobber remains in a fixed position for too long without any fish being caught, the rod automatically reels in and casts again. This would help address the issue where the client gets stuck and prevent the rod from becoming ineffective.

**Describe alternatives you've considered**  
An alternative could be to set a maximum waiting time for each cast. If the time is exceeded without any movement from the bobber, the rod would automatically reel in and cast again, ensuring the mod continues to function properly.

**Additional context**  
This feature would be particularly useful in situations where the client-side visuals get out of sync with the server, ensuring that the fishing process doesn't get stuck due to glitches.

**Comment by North-West-Wind** [comment]
Update v7.1.0 should be available on CurseForge soon. `Check Interval` now also checks if the bobber is stuck, and I also fixed the blurry config menu.
