### ISSUE TITLE
Broken features (possibly linked to version mismatch)

### ISSUE THREAD

**Issue by rsquatre** [North-West-Wind/forge-autofish#8]
**Describe the bug**
Item filter, fishing rod protection and auto replace are not working. I'm not sure if this is linked but the file name and changelog indicate version 2.1.0 while the version field of mod.toml says 2.0.3 so maybe there's no bug and you just accidentally uploaded the wrong file (same thing on both Github and CurseForge 2.1.0 releases).

Edit: Fishing rod protection worked this time but it didn't switch to another fishing rod so maybe it was just confused because of Unbreaking I when it broke last time I tried (like it thought it would last one more use but didn't?).

**To Reproduce**
Regular fishing.

**Expected behavior What is supposed to happen?**
Throwing away filtered items (assuming that's how it's supposed to work), removing low durability rod from hand and using a new one.

**Screenshots**
![version mismatch](https://user-images.githubusercontent.com/10322948/121514358-3692fe80-c9ec-11eb-90df-03924887689b.png)

**Comment by North-West-Wind** [comment]
Alright there are a few changes I need to clarify:
1. Item Filter now only throw items in your inventory, not in hotbar.
2. Auto Replace now only change to fishing rods in hotbar.

I will take a look at Rod Protect

**Comment by North-West-Wind** [comment]
Fixed with 2.1.1
